// frontend/src/routes/app/settings/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';
  import { theme } from '$lib/stores/theme';
  import { session } from '$lib/stores/session';
  import type { UserSettings } from '$lib/stores/user-settings';
  import { userSettings } from '$lib/stores/user-settings';
  import { getLifetimeStatus } from '$lib/nostr/lifetime-status';
  import { getRelayList } from '$lib/nostr/relay-list';
  import { ensureRelayUrlsConnected } from '$lib/nostr/ndk';
  import { api, type AccountSettings } from '$lib/api/client';
  import { config } from '$lib/config';
  import { IS_APPLE_BUILD } from '$lib/build-flags';
  import ApiKeysSection from '$lib/components/ApiKeysSection.svelte';
  import UsernameSection from '$lib/components/UsernameSection.svelte';
  import DeleteAccountSection from '$lib/components/DeleteAccountSection.svelte';
  import LightningAddressSection from '$lib/components/LightningAddressSection.svelte';
  import NwcSection from '$lib/components/NwcSection.svelte';
  import ProfilePictureSection from '$lib/components/ProfilePictureSection.svelte';
  import PrivateKeySection from '$lib/components/PrivateKeySection.svelte';
  import ArchiveDownloadSection from '$lib/components/ArchiveDownloadSection.svelte';

  $: lifetimeStatus = $session.pubkey ? getLifetimeStatus($session.pubkey) : null;
  $: isLifetime = !!(lifetimeStatus && $lifetimeStatus);
  $: archiveDefaultEnabled = isLifetime && (
    $userSettings.archiveAllByDefault || !$userSettings.archiveDefaultManualOverride
  );

  // NIP-65 relay list (kind:10002) for the signed-in user. Displays the
  // relay preferences Deepmarks picked up via NDK's outbox model; stays
  // null if the user has never published one, in which case we fall
  // back to showing the default set.
  $: relayListStore = $session.pubkey ? getRelayList($session.pubkey) : null;
  $: userRelays = relayListStore ? $relayListStore : null;

  let newRelay = '';
  let newBlossom = '';
  let blossomError = '';
  let relayError = '';
  let syncStatus = '';
  let syncLoadedFor = '';
  let syncLoadingFor = '';
  let syncFailedFor = '';
  let settingsSyncReady = false;
  let autoImportedRelaySignature = '';
  $: nip65RelaysToImport = userRelays
    ? userRelays.relays
        .map((r) => relayEntryToSettings(r))
        .filter((r): r is NonNullable<ReturnType<typeof relayEntryToSettings>> => !!r)
        .filter((r) => !$userSettings.relays.some((existing) => existing.url === r.url))
    : [];
  // Profile name + bio + nip05 are intentionally NOT managed here —
  // purpose-built nostr clients (Damus, Primal, Amethyst, …) already
  // own that UX. We do surface:
  //   • lightning address — lets other users zap this curator profile
  //   • profile picture — the extension links here when the user taps
  //     their default avatar; sending them to a separate client just
  //     to set an avatar is bad UX

  function normalizeBlossomUrl(raw: string): string {
    const value = raw.trim();
    if (!value) throw new Error('enter a Blossom server URL');
    const parsed = new URL(value);
    if (parsed.protocol !== 'https:') throw new Error('use an https Blossom server URL');
    if (!parsed.hostname.includes('.') || parsed.hostname === 'localhost' || parsed.hostname.endsWith('.local')) {
      throw new Error('use a public Blossom server hostname');
    }
    return parsed.origin;
  }

  function normalizeRelayUrl(raw: string): string {
    const value = raw.trim().replace(/\/$/, '');
    if (!value) throw new Error('enter a relay URL');
    const parsed = new URL(value);
    if (parsed.protocol !== 'wss:' && parsed.protocol !== 'ws:') {
      throw new Error('use a wss:// relay URL');
    }
    if (!parsed.hostname.includes('.') || parsed.hostname === 'localhost' || parsed.hostname.endsWith('.local')) {
      throw new Error('use a public relay hostname');
    }
    return parsed.toString().replace(/\/$/, '');
  }

  onMount(() => {
    if ($session.pubkey && !$session.signer) syncStatus = 'connect signer to sync';
  });

  $: signerSyncKey = $session.pubkey && $session.signer
    ? `${$session.pubkey}:${$session.signer.kind}`
    : '';

  $: if (
    signerSyncKey &&
    syncLoadedFor !== signerSyncKey &&
    syncLoadingFor !== signerSyncKey &&
    syncFailedFor !== signerSyncKey &&
    $session.pubkey
  ) {
    syncLoadingFor = signerSyncKey;
    void loadSettingsSync($session.pubkey, signerSyncKey);
  }

  $: if ($session.pubkey && !$session.signer && !syncStatus) {
    syncStatus = 'connect signer to sync';
  }

  $: if (settingsSyncReady && userRelays && nip65RelaysToImport.length > 0) {
    const signature = `${userRelays.pubkey}:${userRelays.at}:${nip65RelaysToImport
      .map((r) => `${r.url}:${r.read ? 'r' : ''}${r.write ? 'w' : ''}`)
      .join('|')}`;
    if (signature !== autoImportedRelaySignature) {
      autoImportedRelaySignature = signature;
      void patchSyncedSettings({
        relays: mergeRelays($userSettings.relays, nip65RelaysToImport),
      });
    }
  }

  async function loadSettingsSync(pubkey: string, syncKey = signerSyncKey): Promise<void> {
    void pubkey;
    if (!$session.signer) {
      syncStatus = 'connect signer to sync';
      if (syncLoadingFor === syncKey) syncLoadingFor = '';
      return;
    }
    syncStatus = $session.signer.kind === 'nip07'
      ? 'syncing settings — approve in extension if prompted'
      : 'syncing settings…';
    try {
      const remote = await api.account.getSettings();
      if (remote.updatedAt >= $userSettings.syncedAt) {
        userSettings.update((current) => ({ ...current, ...remote, syncedAt: remote.updatedAt }));
        connectSettingsRelays(remote.relays);
      } else {
        const saved = await api.account.putSettings(toAccountSettings($userSettings));
        userSettings.update((current) => ({ ...current, ...saved, syncedAt: saved.updatedAt }));
        connectSettingsRelays(saved.relays);
      }
      syncStatus = 'settings synced';
      syncLoadedFor = syncKey;
      syncFailedFor = '';
      settingsSyncReady = true;
    } catch (e) {
      syncFailedFor = syncKey;
      syncStatus = `local settings active${(e as Error).message ? ' — connect signer to sync' : ''}`;
    } finally {
      if (syncLoadingFor === syncKey) syncLoadingFor = '';
    }
  }

  async function updateSyncedSettings(next: UserSettings): Promise<void> {
    const optimistic = {
      ...next,
      syncedAt: Math.max(next.syncedAt, Math.floor(Date.now() / 1000)),
    };
    userSettings.set(optimistic);
    connectSettingsRelays(optimistic.relays);
    if (!$session.pubkey || !$session.signer) {
      syncStatus = 'saved locally; connect signer to sync';
      return;
    }
    syncStatus = $session.signer.kind === 'nip07'
      ? 'saving settings — approve in extension if prompted'
      : 'saving settings…';
    try {
      const saved = await api.account.putSettings(toAccountSettings(optimistic));
      userSettings.update((current) => ({ ...current, ...saved, syncedAt: saved.updatedAt }));
      connectSettingsRelays(saved.relays);
      syncStatus = 'settings synced';
      if (signerSyncKey) syncLoadedFor = signerSyncKey;
      syncFailedFor = '';
      settingsSyncReady = true;
    } catch (e) {
      syncStatus = `saved locally; sync failed: ${(e as Error).message}`;
    }
  }

  function connectSettingsRelays(relays: UserSettings['relays']): void {
    ensureRelayUrlsConnected(
      relays.filter((r) => r.read || r.write).map((r) => r.url),
    );
  }

  async function patchSyncedSettings(patch: Partial<UserSettings>): Promise<void> {
    await updateSyncedSettings({ ...$userSettings, ...patch });
  }

  function toAccountSettings(settings: UserSettings): Omit<AccountSettings, 'schemaVersion' | 'updatedAt'> {
    return {
      relays: settings.relays,
      defaultTags: settings.defaultTags,
      defaultVisibility: settings.defaultVisibility,
      archiveAllByDefault: settings.archiveAllByDefault,
      archiveDefaultManualOverride: settings.archiveDefaultManualOverride,
      backupBlossomServers: settings.backupBlossomServers,
    };
  }

  function addRelay() {
    relayError = '';
    try {
      const url = normalizeRelayUrl(newRelay);
      if ($userSettings.relays.some((r) => r.url === url)) {
        newRelay = '';
        return;
      }
      newRelay = '';
      void patchSyncedSettings({
        relays: [...$userSettings.relays, { url, read: true, write: true }],
      });
    } catch (e) {
      relayError = (e as Error).message;
    }
  }

  function updateRelay(url: string, patch: { read?: boolean; write?: boolean }) {
    const relays = $userSettings.relays.map((r) => (
      r.url === url ? { ...r, ...patch } : r
    ));
    void patchSyncedSettings({ relays });
  }

  function removeRelay(url: string) {
    const relays = $userSettings.relays.filter((r) => r.url !== url);
    void patchSyncedSettings({ relays });
  }

  function relayEntryToSettings(entry: { url: string; mode: 'read' | 'write' | 'both' }): UserSettings['relays'][number] | null {
    try {
      const url = normalizeRelayUrl(entry.url);
      return {
        url,
        read: entry.mode !== 'write',
        write: entry.mode !== 'read',
      };
    } catch {
      return null;
    }
  }

  function mergeRelays(
    current: UserSettings['relays'],
    incoming: UserSettings['relays'],
  ): UserSettings['relays'] {
    const byUrl = new Map(current.map((r) => [r.url, r]));
    for (const relay of incoming) {
      if (!byUrl.has(relay.url)) byUrl.set(relay.url, relay);
    }
    return [...byUrl.values()];
  }

  function addBlossomServer() {
    blossomError = '';
    try {
      const url = normalizeBlossomUrl(newBlossom);
      if ($userSettings.backupBlossomServers.includes(url)) {
        newBlossom = '';
        return;
      }
      if ($userSettings.backupBlossomServers.length >= 8) {
        throw new Error('up to 8 backup Blossom servers are supported');
      }
      void patchSyncedSettings({
        backupBlossomServers: [...$userSettings.backupBlossomServers, url],
      });
      newBlossom = '';
    } catch (e) {
      blossomError = (e as Error).message;
    }
  }

  function removeBlossomServer(url: string) {
    void patchSyncedSettings({
      backupBlossomServers: $userSettings.backupBlossomServers.filter((v) => v !== url),
    });
  }
</script>

<svelte:head><title>settings — Deepmarks</title></svelte:head>

<div class="page">
  <h1>settings</h1>
  <p class="sync-status">{syncStatus || 'changes autosave'}</p>

  <PrivateKeySection />

  <section>
    <h2>plan</h2>
    {#if isLifetime}
      <p class="muted">lifetime ✓ — archiving, API keys, and short handles are unlocked.</p>
    {:else if IS_APPLE_BUILD}
      <p class="muted">
        free account — bookmarking works in the app. Lifetime-only features unlock
        automatically here after the identity is upgraded on the website.
      </p>
    {:else}
      <p class="muted">
        free — save private and public bookmarks. lifetime is a one-time
        {config.lifetimePriceSats.toLocaleString('en-US')} sats and unlocks page archiving.
      </p>
      <a href="/app/upgrade" class="upgrade-cta">upgrade to lifetime →</a>
    {/if}
  </section>

  <ProfilePictureSection />

  <LightningAddressSection />

  <NwcSection />

  <section>
    <h2>mobile signer</h2>
    <p class="muted">
      Use the iOS or Android app as a Nostr remote signer for websites and other clients.
      Pair it with a nostrconnect link or QR code.
    </p>
    <a class="upgrade-cta neutral" href="/app/mobile-signer">open mobile signer</a>
  </section>

  <UsernameSection {isLifetime} />

  <section>
    <h2>theme</h2>
    <div class="theme-row">
      <button class:active={$theme === 'light'} on:click={() => theme.set('light')}>light</button>
      <button class:active={$theme === 'dark'} on:click={() => theme.set('dark')}>dark</button>
      <button class:active={$theme === 'auto'} on:click={() => theme.set('auto')}>follow system</button>
    </div>
  </section>

  <section>
    <h2>relays</h2>
    <p class="muted">
      This is the active Deepmarks relay list. Every change autosaves and syncs to the web app,
      mobile app, and browser extensions. Your NIP-65 list from other Nostr apps is automatically
      merged here when found.
    </p>
    <ul class="relay-list">
      {#each $userSettings.relays as r (r.url)}
        <li>
          <code>{r.url}</code>
          <span class="relay-controls">
            <label><input type="checkbox" checked={r.read} on:change={(e) => updateRelay(r.url, { read: e.currentTarget.checked })} /> read</label>
            <label><input type="checkbox" checked={r.write} on:change={(e) => updateRelay(r.url, { write: e.currentTarget.checked })} /> write</label>
            <button class="tiny" type="button" on:click={() => removeRelay(r.url)}>remove</button>
          </span>
        </li>
      {/each}
    </ul>
    <div class="add-relay">
      <input
        type="text"
        placeholder="wss://your-relay.example"
        bind:value={newRelay}
        on:keydown={(e) => e.key === 'Enter' && addRelay()}
      />
      <button class="primary" type="button" on:click={addRelay}>add relay</button>
    </div>
    {#if relayError}<p class="status-error">{relayError}</p>{/if}
    {#if userRelays && userRelays.relays.length > 0}
      <p class="muted">
        NIP-65 relay list found and imported, signed <code>{new Date(userRelays.at * 1000).toLocaleDateString()}</code>.
      </p>
      <ul class="relay-list compact-list">
        {#each userRelays.relays as r (r.url)}
          <li>
            <code>{r.url}</code>
            {#if r.mode !== 'both'}<span class="badge mode-{r.mode}">{r.mode}</span>{/if}
          </li>
        {/each}
      </ul>
    {:else if relayListStore && userRelays === null}
      <p class="muted">looking for your NIP-65 list on connected relays…</p>
      <ul class="relay-list">
        <li><code>{config.deepmarksRelay}</code> <span class="badge">deepmarks</span></li>
        {#each config.defaultRelays as r}
          <li><code>{r}</code></li>
        {/each}
      </ul>
    {:else}
      <p class="muted">default set — sign in to load your NIP-65 list.</p>
      <ul class="relay-list">
        <li><code>{config.deepmarksRelay}</code> <span class="badge">deepmarks</span></li>
        {#each config.defaultRelays as r}
          <li><code>{r}</code></li>
        {/each}
      </ul>
    {/if}
  </section>

  <section>
    <h2>new bookmark defaults</h2>
    <p class="muted">
      These defaults apply when saving from the web app, mobile app, and browser extensions.
    </p>
    <div class="visibility-row">
      <button
        type="button"
        class:active={$userSettings.defaultVisibility === 'private'}
        on:click={() => void patchSyncedSettings({ defaultVisibility: 'private' })}
      >private</button>
      <button
        type="button"
        class:active={$userSettings.defaultVisibility === 'public'}
        on:click={() => void patchSyncedSettings({ defaultVisibility: 'public' })}
      >public</button>
    </div>
  </section>

  <section>
    <h2>site archive storage</h2>
    <p class="muted">
      Lifetime archives are stored on Deepmarks and mirrored to Primal by default. Add your own
      paid or trusted Blossom servers here for extra copies.
    </p>
    {#if !isLifetime}
      <p class="muted">
        Archiving is a lifetime feature. Once this identity is lifetime,
        archive defaults unlock here automatically.
      </p>
      {#if !IS_APPLE_BUILD}
        <a href="/app/upgrade" class="upgrade-cta">upgrade to lifetime →</a>
      {/if}
    {:else}
      <label class="toggle">
        <input
          type="checkbox"
          checked={archiveDefaultEnabled}
          on:change={(e) =>
            void patchSyncedSettings({
              archiveAllByDefault: e.currentTarget.checked,
              archiveDefaultManualOverride: true,
            })}
        />
        <span>
          archive every bookmark by default
          <small>— included with lifetime membership</small>
        </span>
      </label>
      <div class="blossom-list">
        {#if $userSettings.backupBlossomServers.length === 0}
          <p class="muted compact">no personal backup servers yet.</p>
        {:else}
          <ul class="relay-list">
            {#each $userSettings.backupBlossomServers as url}
              <li>
                <code>{url}</code>
                <button class="tiny" type="button" on:click={() => removeBlossomServer(url)}>remove</button>
              </li>
            {/each}
          </ul>
        {/if}
        <div class="add-relay">
          <input
            type="text"
            placeholder="https://blossom.example.com"
            bind:value={newBlossom}
            on:keydown={(e) => e.key === 'Enter' && addBlossomServer()}
          />
          <button class="primary" type="button" on:click={addBlossomServer}>add backup</button>
        </div>
        {#if blossomError}<p class="status-error">{blossomError}</p>{/if}
      </div>
    {/if}
  </section>

  <ArchiveDownloadSection />

  <ApiKeysSection />

  <section>
    <h2>sign out</h2>
    <p class="muted">sign out of this browser — your nostr data stays on the relays.</p>
    <button
      type="button"
      class="ghost"
      on:click={() => { session.logout(); void goto('/'); }}
    >sign out</button>
  </section>

  <DeleteAccountSection />
</div>

<style>
  .page {
    max-width: 720px;
    margin: 0 auto;
    padding: 36px 24px 60px;
    color: var(--ink-deep);
    font-size: 14px;
  }
  h1 { font-family: 'Space Grotesk', Inter, sans-serif; font-size: 30px; color: var(--ink-deep); letter-spacing: 0; margin: 0 0 8px; }
  section { margin-top: 32px; }
  section h2 {
    font-size: 12px;
    text-transform: uppercase;
    color: var(--ink-deep);
    letter-spacing: 0;
    margin: 0 0 12px;
    padding-bottom: 6px;
    font-weight: 600;
    border-bottom: 1px solid var(--rule);
  }
  code { font-family: 'Courier New', monospace; font-size: 12px; color: var(--ink-deep); word-break: break-all; }
  .theme-row { display: flex; gap: 8px; }
  .theme-row button,
  .visibility-row button { background: var(--surface); border: 1px solid var(--rule); color: var(--ink); padding: 6px 14px; border-radius: 100px; cursor: pointer; font-size: 13px; }
  .theme-row button.active,
  .visibility-row button.active { border-color: var(--coral); color: var(--coral); }
  .visibility-row { display: flex; gap: 8px; flex-wrap: wrap; }
  .muted { color: var(--ink-deep); font-size: 14px; line-height: 1.6; }
  .upgrade-cta {
    display: inline-block; margin-top: 8px;
    background: var(--coral); color: var(--on-coral) !important;
    padding: 8px 16px; border-radius: 100px;
    font-size: 14px; font-weight: 500; text-decoration: none;
  }
  .upgrade-cta:hover { background: var(--coral-deep); text-decoration: none; }
  .upgrade-cta.neutral { background: var(--surface); color: var(--ink-deep) !important; border: 1px solid var(--rule); }
  .upgrade-cta.neutral:hover { border-color: var(--coral); color: var(--coral-deep) !important; background: var(--surface); }
  .relay-list { list-style: none; padding: 0; margin: 0 0 12px; }
  .relay-list li { padding: 6px 0; border-bottom: 1px dashed var(--rule); display: flex; justify-content: space-between; align-items: center; gap: 8px; font-size: 13px; color: var(--ink-deep); }
  .compact-list { margin-top: 8px; opacity: 0.85; }
  .relay-controls { display: inline-flex; align-items: center; gap: 8px; flex-wrap: wrap; justify-content: flex-end; }
  .relay-controls label { display: inline-flex; align-items: center; gap: 3px; color: var(--ink); font-size: 12px; }
  .sync-status { color: var(--ink); font-size: 13px; margin: -2px 0 10px; }
  .badge { background: var(--coral-soft); color: var(--coral-deep); padding: 1px 8px; border-radius: 10px; font-size: 10px; text-transform: uppercase; letter-spacing: 0; font-weight: 600; }
  .badge.mode-read { background: var(--paper-warm); color: var(--ink-deep); }
  .badge.mode-write { background: var(--paper-warm); color: var(--ink-deep); }
  .add-relay { display: flex; gap: 8px; }
  .add-relay input { flex: 1; padding: 8px 10px; border: 1px solid var(--rule); border-radius: 6px; background: var(--surface); color: var(--ink-deep); font-family: 'Courier New', monospace; font-size: 13px; }
  .primary { background: var(--coral); color: var(--on-coral); border: 0; padding: 8px 16px; border-radius: 100px; cursor: pointer; font-size: 14px; font-family: inherit; }
  .primary:hover:not(:disabled) { background: var(--coral-deep); }
  .primary:disabled { opacity: 0.5; cursor: not-allowed; }
  .blossom-list { margin-top: 14px; }
  .compact { margin: 0 0 10px; }
  .tiny { background: transparent; border: 1px solid var(--rule); color: var(--ink); padding: 4px 8px; border-radius: 999px; cursor: pointer; font-size: 12px; }
  .tiny:hover { border-color: var(--coral); color: var(--coral-deep); }
  .tiny:disabled { opacity: 0.55; cursor: default; }
  .status-error { color: var(--coral-deep); background: var(--coral-soft); border-radius: 6px; padding: 8px 10px; font-size: 13px; margin: 8px 0 0; }
  .ghost { background: transparent; border: 1px solid var(--rule); color: var(--ink-deep); padding: 8px 16px; border-radius: 100px; cursor: pointer; font-size: 14px; }
  .ghost:hover { border-color: var(--coral); color: var(--coral-deep); }
  .toggle { display: flex; align-items: flex-start; gap: 10px; margin-top: 12px; cursor: pointer; font-size: 14px; color: var(--ink-deep); }
  .toggle input { margin-top: 3px; flex-shrink: 0; }
  .toggle small { display: block; color: var(--ink); font-size: 12px; margin-top: 2px; }
</style>

// browser-extension/src/popup/screens/Settings.tsx
// Settings — pixel-spirit-matches popup-screens-3.jsx ScreenSettings.
//
// The handoff specifies a 720×560 settings page that opens in its own
// tab (sidebar + main pane). Building that as a separate /settings.html
// is a v2 — for v1 we render the same five sections inline in the
// popup, scrollable. Same data model, same routes.
//
// Sections: Relays · Archiving · Default tags · Saved logins · Account.

import { useEffect, useState } from 'react';
import { colors, fonts, fontSize, lineHeight, space, radius } from '../../shared/tokens.js';
import { Pennant } from '../../shared/Pennant.js';
import { BackButton } from '../components/BackButton.js';
import { TagInput } from '../components/TagInput.js';
import {
  getSettings, importNip65Relays, patchSettings, pushSettingsToServer, revokeLogin, savedLoginLabel,
  type RelayConfig, type Settings as SettingsT, type BookmarkVisibility, type PublishMode,
} from '../../lib/settings-store.js';
import { discoverUserRelays } from '../../lib/nostr.js';
import { syncSettingsAndPublishedRelays } from '../../lib/relay-sync.js';
import {
  nsecStore,
  type NsecState,
} from '../../lib/nsec-store.js';
import { getLifetimeStatus } from '../../lib/archive.js';
import { IS_APPLE_BUILD } from '../../lib/build-flags.js';
import { clearNwc } from '../../lib/nwc-store.js';
import { ArchiveDefaultRow, NwcSection, SecuritySection } from './settings/AccountSections.js';
import { nip19 } from 'nostr-tools';

export function Settings({ state, onStateChange, onSignOut }: {
  state: NsecState;
  onStateChange: (s: NsecState) => void;
  onSignOut: () => void;
}) {
  const account = state; // local alias, lets the existing JSX keep using `account.pubkey` etc.
  const [settings, setSettings] = useState<SettingsT | null>(null);
  const [newRelay, setNewRelay] = useState('');
  const [newBlossom, setNewBlossom] = useState('');
  const [blossomError, setBlossomError] = useState<string | null>(null);
  const [isLifetime, setIsLifetime] = useState<boolean | null>(null);
  const [syncStatus, setSyncStatus] = useState('');
  const [relayScanStatus, setRelayScanStatus] = useState('');
  // Two-tap inline confirm for sign-out. window.confirm() is blocked
  // inside Safari Web Extension popups (the dialog never appears and
  // confirm() returns false), so we replace it with an in-popup
  // "click again to confirm" state. Auto-resets after 4s.
  const [signOutArmed, setSignOutArmed] = useState(false);
  useEffect(() => {
    if (!signOutArmed) return;
    const t = setTimeout(() => setSignOutArmed(false), 4000);
    return () => clearTimeout(t);
  }, [signOutArmed]);

  useEffect(() => {
    void getSettings().then(setSettings);
    if (state.nsecHex) {
      setSyncStatus('syncing settings...');
      void syncSettingsAndPublishedRelays(state.pubkey, state.nsecHex)
        .then((next) => {
          setSettings(next);
          setSyncStatus('settings synced');
        })
        .catch(() => setSyncStatus('local settings active'));
    }
  }, [state.nsecHex]);

  // Look up lifetime status on mount + every time the popup opens
  // while Settings is the active screen. Cheap unauthenticated GET.
  useEffect(() => {
    if (!state.pubkey) return;
    void getLifetimeStatus(state.pubkey)
      .then((s) => setIsLifetime(s.isLifetimeMember))
      .catch(() => setIsLifetime(false));
  }, [state.pubkey]);
  if (!settings) return null;
  const archiveDefaultEffective =
    isLifetime === true && (settings.archiveDefault || !settings.archiveDefaultManualOverride);

  async function update(patch: Partial<SettingsT>) {
    const shouldSync = hasSyncedSetting(patch);
    const next = await patchSettings(shouldSync
      ? { ...patch, pendingSync: true, syncedAt: Date.now() }
      : patch);
    setSettings(next);
    if (!state.nsecHex || !shouldSync) return;
    setSyncStatus('saving settings...');
    try {
      const synced = await pushSettingsToServer(state.nsecHex, next);
      setSettings(synced);
      setSyncStatus('settings synced');
    } catch {
      setSyncStatus('saved locally; sync failed');
    }
  }

  async function addRelay() {
    const url = newRelay.trim();
    if (!/^wss?:\/\//.test(url)) return;
    if (settings!.relays.some((r) => r.url === url)) return;
    setNewRelay('');
    await update({ relays: [...settings!.relays, { url, read: true, write: true }] });
  }

  async function findRelays(opts: { quiet?: boolean } = {}) {
    if (!state.pubkey) return;
    if (!opts.quiet) setRelayScanStatus('looking for relays...');
    try {
      const discovered = await discoverUserRelays(state.pubkey);
      if (discovered.length === 0) {
        if (!opts.quiet) setRelayScanStatus('no NIP-65 relays found yet');
        return;
      }
      const next = await importNip65Relays(discovered);
      setSettings(next);
      if (state.nsecHex) {
        await pushSettingsToServer(state.nsecHex, next).catch(() => undefined);
      }
      if (!opts.quiet) {
        setRelayScanStatus(`synced ${next.relays.length} published relay${next.relays.length === 1 ? '' : 's'} from NIP-65`);
      }
    } catch (e) {
      if (!opts.quiet) setRelayScanStatus(`relay lookup failed: ${(e as Error).message}`);
    }
  }

  async function addBlossomServer() {
    setBlossomError(null);
    try {
      const url = normalizeBlossomUrl(newBlossom);
      if (settings!.backupBlossomServers.includes(url)) {
        setNewBlossom('');
        return;
      }
      if (settings!.backupBlossomServers.length >= 8) {
        throw new Error('up to 8 backup Blossom servers are supported');
      }
      setNewBlossom('');
      await update({ backupBlossomServers: [...settings!.backupBlossomServers, url] });
    } catch (e) {
      setBlossomError((e as Error).message);
    }
  }

  async function removeBlossomServer(url: string) {
    await update({ backupBlossomServers: settings!.backupBlossomServers.filter((v) => v !== url) });
  }

  return (
    <div style={page}>
      <header style={header}>
        <div style={brandRow}>
          <BackButton />
          <Pennant size={14} />
          <span style={brand}>Deepmarks</span>
        </div>
      </header>

      <div style={body}>
        {syncStatus && <div style={emptyHint}>{syncStatus}</div>}
        <Section title="Relays">
          <SelectRow
            label="Publish route"
            value={settings.publishMode}
            options={[
              ['deepmarks', 'via Deepmarks server (privacy)'],
              ['direct', 'direct to write relays'],
            ]}
            onChange={(v) => void update({ publishMode: v as PublishMode })}
          />
          <div style={emptyHint}>
            Server mode keeps your browser IP off public relays; direct mode publishes to relays marked w below.
          </div>
          <div style={relayList}>
            {settings.relays.map((r, i) => (
              <RelayRow
                key={r.url}
                relay={r}
                onChange={(next) => {
                  const updated = [...settings.relays];
                  updated[i] = next;
                  void update({ relays: updated });
                }}
                onDelete={() => void update({ relays: settings.relays.filter((_, j) => j !== i) })}
              />
            ))}
          </div>
          <div style={addRow}>
            <input
              type="text"
              placeholder="wss://relay.example.com"
              value={newRelay}
              onChange={(e) => setNewRelay(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') void addRelay(); }}
              style={input}
            />
            <button style={addBtn} onClick={() => void addRelay()}>+ Add relay</button>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            <button style={secondaryBtn} onClick={() => void findRelays()} disabled={!state.pubkey}>
              rescan NIP-65 relays
            </button>
            {relayScanStatus && <div style={emptyHint}>{relayScanStatus}</div>}
          </div>
        </Section>

        {/* Apple build: the whole section disappears for non-members.
            An "Archiving" heading over membership copy is what App
            Review flagged (guideline 3.1.3(b)); members just see the
            working controls with no purchase reference. */}
        {(!IS_APPLE_BUILD || isLifetime) && (
        <Section title="Archiving">
          <ArchiveDefaultRow
            value={archiveDefaultEffective}
            isLifetime={isLifetime}
            nsecHex={state.nsecHex}
            locked={state.locked}
            onChange={(v) => void update({ archiveDefault: v, archiveDefaultManualOverride: true })}
            onUpgraded={() => void getLifetimeStatus(state.pubkey!).then((s) => setIsLifetime(s.isLifetimeMember))}
          />
          {isLifetime && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginTop: 14 }}>
              <div style={emptyHint}>
                Deepmarks and Primal are used by default. Add paid or trusted Blossom servers you control for extra copies.
              </div>
              {settings.backupBlossomServers.length > 0 && (
                <div style={relayList}>
                  {settings.backupBlossomServers.map((url) => (
                    <div key={url} style={loginRow}>
                      <div style={loginMain}>
                        <div style={{ ...loginHost, fontFamily: fonts.mono, fontSize: fontSize.monoSmall }}>{url}</div>
                      </div>
                      <button style={revokeBtn} onClick={() => void removeBlossomServer(url)}>
                        remove
                      </button>
                    </div>
                  ))}
                </div>
              )}
              <div style={addRow}>
                <input
                  type="text"
                  placeholder="https://blossom.example.com"
                  value={newBlossom}
                  onChange={(e) => setNewBlossom(e.target.value)}
                  onKeyDown={(e) => { if (e.key === 'Enter') void addBlossomServer(); }}
                  style={input}
                />
                <button style={addBtn} onClick={() => void addBlossomServer()}>+ Add backup</button>
              </div>
              {blossomError && (
                <div style={{ padding: 8, background: '#fbe9e3', color: '#8b2f17', borderRadius: 3, fontSize: 12 }}>
                  {blossomError}
                </div>
              )}
            </div>
          )}
        </Section>
        )}

        <Section title="New bookmark visibility">
          <SelectRow
            label="Default for new bookmarks"
            value={settings.defaultVisibility}
            options={[['private', 'private (encrypted to your key)'], ['public', 'public (visible on Nostr)']]}
            onChange={(v) => void update({ defaultVisibility: v as BookmarkVisibility })}
          />
        </Section>

        <Section title="Default tags">
          <TagInput
            value={settings.defaultTags}
            onChange={(v) => void update({ defaultTags: v })}
            placeholder="add a default tag…"
          />
        </Section>

        <Section title="Lightning wallet (NWC)">
          <NwcSection account={state} />
        </Section>

        <Section title="Saved logins">
          {settings.savedLogins.length === 0 ? (
            <div style={emptyHint}>No "Forever" grants yet. Sites you approve to sign with your key will show up here.</div>
          ) : (
            settings.savedLogins.map((l) => (
              <div key={l.origin} style={loginRow}>
                <div style={loginFavicon}>{originHost(l.origin).charAt(0).toUpperCase()}</div>
                <div style={loginMain}>
                  <div style={loginHost}>{originHost(l.origin)}</div>
                  <div style={loginMeta}>{savedLoginLabel(l)} · last used {relTime(l.lastUsedAt)}</div>
                </div>
                <button
                  style={revokeBtn}
                  onClick={async () => { await revokeLogin(l.origin, l); setSettings(await getSettings()); }}
                >
                  revoke
                </button>
              </div>
            ))
          )}
        </Section>

        <Section title="Security">
          <SecuritySection state={account} onStateChange={onStateChange} />
        </Section>

        <Section title="Account">
          <label style={accountLabel}>npub</label>
          <input
            readOnly
            value={account.pubkey ? nip19.npubEncode(account.pubkey) : ''}
            style={{ ...input, fontFamily: fonts.mono, fontFeatureSettings: '"ss01","tnum"', fontSize: fontSize.monoSmall }}
            onClick={(e) => (e.target as HTMLInputElement).select()}
          />
          {account.pubkey && (
            <a
              href={`https://deepmarks.org/u/${account.pubkey}`}
              target="_blank" rel="noreferrer"
              style={{ ...secondaryBtn, textAlign: 'center', textDecoration: 'none', display: 'block' }}
            >
              View on deepmarks ↗
            </a>
          )}
          <button
            style={dangerBtn}
            onClick={async () => {
              if (!signOutArmed) {
                setSignOutArmed(true);
                return;
              }
              await clearNwc({ sync: false });
              await nsecStore.clear();
              onSignOut();
            }}
          >
            {signOutArmed ? 'Click again to confirm — clears your nsec' : 'Sign out'}
          </button>
        </Section>
      </div>
    </div>
  );
}

function hasSyncedSetting(patch: Partial<SettingsT>): boolean {
  return 'relays' in patch ||
    'defaultTags' in patch ||
    'archiveDefault' in patch ||
    'archiveDefaultManualOverride' in patch ||
    'defaultVisibility' in patch ||
    'backupBlossomServers' in patch;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={section}>
      <h2 style={sectionH2}>{title}</h2>
      <div style={sectionBody}>{children}</div>
    </section>
  );
}

function RelayRow({ relay, onChange, onDelete }: {
  relay: RelayConfig;
  onChange: (next: RelayConfig) => void;
  onDelete: () => void;
}) {
  return (
    <div style={relayRow}>
      <code style={relayUrl}>{relay.url}</code>
      <ToggleSmall label="r" value={relay.read} onChange={(v) => onChange({ ...relay, read: v })} />
      <ToggleSmall label="w" value={relay.write} onChange={(v) => onChange({ ...relay, write: v })} />
      <button style={relayDelete} onClick={onDelete} aria-label={`remove ${relay.url}`}>×</button>
    </div>
  );
}

function ToggleSmall({ label, value, onChange }: { label: string; value: boolean; onChange: (v: boolean) => void }) {
  return (
    <button
      type="button"
      onClick={() => onChange(!value)}
      title={label === 'r' ? 'read' : 'write'}
      style={{
        ...toggleSmall,
        background: value ? colors.accent : 'transparent',
        color: value ? '#fff' : colors.muted,
        borderColor: value ? colors.accent : colors.hairline,
      }}
      aria-pressed={value}
    >
      {label}
    </button>
  );
}

function SelectRow({ label, value, options, onChange }: {
  label: string;
  value: string;
  options: [string, string][];
  onChange: (v: string) => void;
}) {
  return (
    <div style={toggleRow}>
      <span style={toggleRowLabel}>{label}</span>
      <select value={value} onChange={(e) => onChange(e.target.value)} style={select}>
        {options.map(([v, l]) => <option key={v} value={v}>{l}</option>)}
      </select>
    </div>
  );
}

function originHost(origin: string): string {
  try { return new URL(origin).hostname; } catch { return origin; }
}
function normalizeBlossomUrl(raw: string): string {
  const value = raw.trim();
  if (!value) throw new Error('enter a Blossom server URL');
  const parsed = new URL(value);
  if (parsed.protocol !== 'https:') throw new Error('use an https Blossom server URL');
  if (!parsed.hostname.includes('.') || parsed.hostname === 'localhost' || parsed.hostname.endsWith('.local')) {
    throw new Error('use a public Blossom server hostname');
  }
  return parsed.origin;
}
function relTime(unix: number): string {
  const d = Math.floor(Date.now() / 1000) - unix;
  if (d < 60) return 'just now';
  if (d < 3600) return `${Math.floor(d / 60)}m ago`;
  if (d < 86400) return `${Math.floor(d / 3600)}h ago`;
  return `${Math.floor(d / 86400)}d ago`;
}

// ── Styles

const page: React.CSSProperties = {
  height: '100%', display: 'flex', flexDirection: 'column',
  background: colors.paper, color: colors.ink, fontFamily: fonts.sans,
};
const header: React.CSSProperties = {
  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  padding: `${space.lg}px ${space.xl}px`,
  borderBottom: `1px solid ${colors.hairline}`,
};
const brandRow: React.CSSProperties = { display: 'flex', alignItems: 'center', gap: 8 };
const brand: React.CSSProperties = {
  fontFamily: fonts.mono, fontFeatureSettings: '"ss01","tnum"',
  fontSize: fontSize.bodyMicro, fontWeight: 500, color: colors.accent,
};
const body: React.CSSProperties = {
  flex: 1, padding: `${space.lg}px ${space.xl}px`,
  overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: space.xl,
};
const section: React.CSSProperties = { display: 'flex', flexDirection: 'column', gap: space.sm };
const sectionH2: React.CSSProperties = {
  margin: 0, fontSize: fontSize.bodySmall, fontWeight: 500, color: colors.ink,
};
const sectionBody: React.CSSProperties = { display: 'flex', flexDirection: 'column', gap: space.sm };
const relayList: React.CSSProperties = { display: 'flex', flexDirection: 'column', gap: 4 };
const relayRow: React.CSSProperties = {
  display: 'flex', alignItems: 'center', gap: space.sm,
  padding: `${space.xs}px ${space.sm}px`,
  border: `1px solid ${colors.hairlineSoft}`, borderRadius: radius.std,
  background: '#fff',
};
const relayUrl: React.CSSProperties = {
  flex: 1, minWidth: 0,
  fontFamily: fonts.mono, fontFeatureSettings: '"ss01","tnum"',
  fontSize: fontSize.monoSmall, color: colors.inkSoft,
  whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
};
const relayDelete: React.CSSProperties = {
  background: 'transparent', border: 'none', color: colors.muted,
  cursor: 'pointer', fontSize: 14, padding: '0 4px',
};
const addRow: React.CSSProperties = { display: 'flex', gap: space.sm, marginTop: space.sm };
const input: React.CSSProperties = {
  flex: 1, boxSizing: 'border-box', padding: `${space.sm}px ${space.lg}px`,
  border: `1px solid ${colors.hairline}`, borderRadius: radius.std,
  background: '#fff', color: colors.ink, fontSize: fontSize.bodyMicro,
  fontFamily: fonts.sans, outline: 'none',
};
const addBtn: React.CSSProperties = {
  padding: `${space.sm}px ${space.lg}px`,
  background: 'transparent', border: `1px solid ${colors.hairline}`,
  borderRadius: radius.std, cursor: 'pointer', fontSize: fontSize.metaSmall, color: colors.inkSoft,
  whiteSpace: 'nowrap',
};
const toggleRow: React.CSSProperties = {
  display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: space.lg,
  padding: `${space.xs}px 0`,
};
const toggleRowLabel: React.CSSProperties = {
  fontSize: fontSize.bodySmall, color: colors.inkSoft, lineHeight: lineHeight.body,
};
const toggleSmall: React.CSSProperties = {
  width: 22, height: 18, fontSize: 10, fontFamily: fonts.mono,
  border: '1px solid', borderRadius: radius.badge, cursor: 'pointer',
  display: 'flex', alignItems: 'center', justifyContent: 'center',
};
const select: React.CSSProperties = {
  padding: `${space.xs}px ${space.sm}px`,
  border: `1px solid ${colors.hairline}`, borderRadius: radius.std,
  background: '#fff', fontSize: fontSize.metaSmall, fontFamily: fonts.sans, color: colors.inkSoft,
};
const emptyHint: React.CSSProperties = {
  fontSize: fontSize.metaSmall, color: colors.muted, lineHeight: lineHeight.body,
};
const loginRow: React.CSSProperties = {
  display: 'flex', alignItems: 'center', gap: space.sm,
  padding: `${space.sm}px 0`, borderBottom: `1px solid ${colors.hairlineSoft}`,
};
const loginFavicon: React.CSSProperties = {
  width: 18, height: 18, borderRadius: 2, background: colors.tagBg,
  display: 'flex', alignItems: 'center', justifyContent: 'center',
  fontSize: 10, fontWeight: 600, color: colors.muted, flexShrink: 0,
};
const loginMain: React.CSSProperties = { flex: 1, minWidth: 0 };
const loginHost: React.CSSProperties = {
  fontSize: fontSize.metaSmall, color: colors.ink, fontWeight: 500,
};
const loginMeta: React.CSSProperties = {
  fontFamily: fonts.mono, fontFeatureSettings: '"ss01","tnum"',
  fontSize: fontSize.uppercaseLabel, color: colors.muted,
};
const revokeBtn: React.CSSProperties = {
  background: 'transparent', border: 'none', color: colors.muted,
  fontSize: fontSize.uppercaseLabel, cursor: 'pointer', textTransform: 'uppercase',
  letterSpacing: '0.08em',
};
const accountLabel: React.CSSProperties = {
  display: 'block', fontFamily: fonts.mono, fontFeatureSettings: '"ss01","tnum"',
  fontSize: fontSize.uppercaseLabel, letterSpacing: '0.08em', fontWeight: 500,
  color: colors.muted, textTransform: 'uppercase', marginBottom: 4,
};
const secondaryBtn: React.CSSProperties = {
  marginTop: space.sm,
  padding: `${space.sm}px ${space.lg}px`,
  background: 'transparent', border: `1px solid ${colors.hairline}`,
  borderRadius: radius.std, fontSize: fontSize.metaSmall, color: colors.inkSoft,
  cursor: 'pointer',
};
const dangerBtn: React.CSSProperties = {
  marginTop: space.sm,
  padding: `${space.sm}px ${space.lg}px`,
  background: 'transparent', border: `1px solid ${colors.warn}`,
  borderRadius: radius.std, fontSize: fontSize.metaSmall, color: colors.warn,
  cursor: 'pointer',
};
